// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1DAL.ConText;

#nullable disable

namespace _1DAL.Migrations
{
    [DbContext(typeof(DBContextDienThoai))]
    [Migration("20230515063043_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1DAL.Models.ChucVu", b =>
                {
                    b.Property<int>("MaCV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCV"), 1L, 1);

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVu", (string)null);

                    b.HasData(
                        new
                        {
                            MaCV = 1,
                            TenCV = "Quản lý"
                        },
                        new
                        {
                            MaCV = 2,
                            TenCV = "Nhân viên"
                        });
                });

            modelBuilder.Entity("_1DAL.Models.DienThoai", b =>
                {
                    b.Property<int>("MaDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDT"), 1L, 1);

                    b.Property<string>("TenDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDT");

                    b.ToTable("DienThoai", (string)null);

                    b.HasData(
                        new
                        {
                            MaDT = 1,
                            TenDT = "Iphone 14 Pro Max",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDT = 2,
                            TenDT = "Realme note 9 pro",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("_1DAL.Models.DienThoaiCT", b =>
                {
                    b.Property<int>("MaDTCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDTCT"), 1L, 1);

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("GiaNhap")
                        .HasColumnType("int");

                    b.Property<string>("LinkAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDT")
                        .HasColumnType("int");

                    b.Property<int>("MaDungLuong")
                        .HasColumnType("int");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<int>("MaImei")
                        .HasColumnType("int");

                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<string>("MaQR")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDTCT");

                    b.HasIndex("MaDT");

                    b.HasIndex("MaDungLuong");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaImei");

                    b.HasIndex("MaMau");

                    b.ToTable("DienThoaiCT", (string)null);

                    b.HasData(
                        new
                        {
                            MaDTCT = 1,
                            GiaBan = 110000,
                            GiaNhap = 100000,
                            LinkAnh = "",
                            MaDT = 1,
                            MaDungLuong = 1,
                            MaHang = 1,
                            MaImei = 1,
                            MaMau = 1,
                            MaQR = "12345",
                            SoLuong = 50,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("_1DAL.Models.DungLuong", b =>
                {
                    b.Property<int>("MaDungLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDungLuong"), 1L, 1);

                    b.Property<string>("SoDungLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SoDungLuong");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDungLuong");

                    b.ToTable("DungLuong", (string)null);

                    b.HasData(
                        new
                        {
                            MaDungLuong = 1,
                            SoDungLuong = "8gb Ram/ 124gb bo nho",
                            TrangThai = 1
                        },
                        new
                        {
                            MaDungLuong = 2,
                            SoDungLuong = "6gb Ram/ 64gb bo nho",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("_1DAL.Models.HangSX", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"), 1L, 1);

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHang");

                    b.ToTable("HangSX", (string)null);

                    b.HasData(
                        new
                        {
                            MaHang = 1,
                            TenHang = "Apple",
                            TrangThai = 1
                        },
                        new
                        {
                            MaHang = 2,
                            TenHang = "Realme",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("_1DAL.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"), 1L, 1);

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBan")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDTKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("_1DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("MaDTCT")
                        .HasColumnType("int");

                    b.Property<int>("MaHD")
                        .HasColumnType("int");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaDTCT", "MaHD");

                    b.HasIndex("MaHD");

                    b.ToTable("HoaDonCT", (string)null);
                });

            modelBuilder.Entity("_1DAL.Models.Imei", b =>
                {
                    b.Property<int>("MaImei")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaImei"), 1L, 1);

                    b.Property<string>("TenImei")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaImei");

                    b.ToTable("Imei", (string)null);

                    b.HasData(
                        new
                        {
                            MaImei = 1,
                            TenImei = "0123456789",
                            TrangThai = true
                        },
                        new
                        {
                            MaImei = 2,
                            TenImei = "0123456788",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("_1DAL.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang", (string)null);

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            DiaChi = "Hà Nam",
                            Diem = 50000,
                            GioiTinh = true,
                            SDT = "0336253482",
                            TenKH = "Ngô Quốc Mạnh"
                        },
                        new
                        {
                            MaKH = 2,
                            DiaChi = "Hà Nội",
                            Diem = 50000,
                            GioiTinh = true,
                            SDT = "0123456789",
                            TenKH = "Chuyên Xem Chùa"
                        },
                        new
                        {
                            MaKH = 3,
                            DiaChi = "không rõ",
                            Diem = 0,
                            GioiTinh = true,
                            SDT = "0",
                            TenKH = "Khách Vãng Lai"
                        });
                });

            modelBuilder.Entity("_1DAL.Models.MauSac", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMau"), 1L, 1);

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaMau");

                    b.ToTable("MauSac", (string)null);

                    b.HasData(
                        new
                        {
                            MaMau = 1,
                            TenMau = "Xanh",
                            TrangThai = 1
                        },
                        new
                        {
                            MaMau = 2,
                            TenMau = "Tim",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("_1DAL.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaCV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaCV");

                    b.ToTable("NhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            MaNV = 2,
                            DiaChi = "Tuyên Quang",
                            GioiTinh = 1,
                            MaCV = 2,
                            NgaySinh = new DateTime(2023, 5, 15, 13, 30, 43, 484, DateTimeKind.Local).AddTicks(5551),
                            SDT = "0379702133",
                            TenNV = "Nguyễn Văn Đạo",
                            TrangThai = 0,
                            matKhau = "123"
                        },
                        new
                        {
                            MaNV = 1,
                            DiaChi = "Hà Nam",
                            GioiTinh = 1,
                            MaCV = 1,
                            NgaySinh = new DateTime(2023, 5, 15, 13, 30, 43, 484, DateTimeKind.Local).AddTicks(5560),
                            SDT = "0336253482",
                            TenNV = "Ngô Quốc Mạnh",
                            TrangThai = 0,
                            matKhau = "123"
                        });
                });

            modelBuilder.Entity("_1DAL.Models.DienThoaiCT", b =>
                {
                    b.HasOne("_1DAL.Models.DienThoai", "DienThoaiS")
                        .WithMany("DienThoaiCTS")
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1DAL.Models.DungLuong", "DungLuongS")
                        .WithMany("DienThoaiCTS")
                        .HasForeignKey("MaDungLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1DAL.Models.HangSX", "HangSXS")
                        .WithMany("DienThoaiCTS")
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1DAL.Models.Imei", "ImeiS")
                        .WithMany("DienThoaiCTs")
                        .HasForeignKey("MaImei")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1DAL.Models.MauSac", "MauSacS")
                        .WithMany("DienThoaiCTS")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DienThoaiS");

                    b.Navigation("DungLuongS");

                    b.Navigation("HangSXS");

                    b.Navigation("ImeiS");

                    b.Navigation("MauSacS");
                });

            modelBuilder.Entity("_1DAL.Models.HoaDon", b =>
                {
                    b.HasOne("_1DAL.Models.KhachHang", "KhachHangS")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1DAL.Models.NhanVien", "NhanVienS")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHangS");

                    b.Navigation("NhanVienS");
                });

            modelBuilder.Entity("_1DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1DAL.Models.DienThoaiCT", "DienThoaiCTS")
                        .WithMany("HoaDonCTs")
                        .HasForeignKey("MaDTCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1DAL.Models.HoaDon", "HoaDonS")
                        .WithMany("HoaDonChiTietS")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DienThoaiCTS");

                    b.Navigation("HoaDonS");
                });

            modelBuilder.Entity("_1DAL.Models.NhanVien", b =>
                {
                    b.HasOne("_1DAL.Models.ChucVu", "ChucVuS")
                        .WithMany("NhanVienS")
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVuS");
                });

            modelBuilder.Entity("_1DAL.Models.ChucVu", b =>
                {
                    b.Navigation("NhanVienS");
                });

            modelBuilder.Entity("_1DAL.Models.DienThoai", b =>
                {
                    b.Navigation("DienThoaiCTS");
                });

            modelBuilder.Entity("_1DAL.Models.DienThoaiCT", b =>
                {
                    b.Navigation("HoaDonCTs");
                });

            modelBuilder.Entity("_1DAL.Models.DungLuong", b =>
                {
                    b.Navigation("DienThoaiCTS");
                });

            modelBuilder.Entity("_1DAL.Models.HangSX", b =>
                {
                    b.Navigation("DienThoaiCTS");
                });

            modelBuilder.Entity("_1DAL.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTietS");
                });

            modelBuilder.Entity("_1DAL.Models.Imei", b =>
                {
                    b.Navigation("DienThoaiCTs");
                });

            modelBuilder.Entity("_1DAL.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1DAL.Models.MauSac", b =>
                {
                    b.Navigation("DienThoaiCTS");
                });

            modelBuilder.Entity("_1DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
